apps/alpsbte-web/src/app/app.tsx, apps/alpsbte-web/src/styles.scss, libs/home/src/lib/home.tsx, libs/shared/components/src/lib/header/header.scss, libs/shared/components/src/lib/header/header.tsx, workspace.json
Note to self: when generating an component **DO NOT** name the file `componen.module.scss`. The module part will not be redered in the app!
=> Closes #13

libs/home/src/components/home-content-section/home-content-section.spec.tsx, libs/home/src/components/home-content-section/home-content-section.tsx, libs/home/src/components/home-heading/home-heading.spec.tsx, libs/home/src/components/home-heading/home-heading.tsx, workspace.json
=> Added Home Content Section

libs/about-us/src/lib/about-us.tsx, libs/application/src/lib/application.tsx, libs/home/src/lib/home.spec.tsx, libs/shared/components/src/lib/header/header.spec.tsx
Adding properties to the testing componenents should fix all tests and the pipelines should work now.
=> Closes #16 fix all tests

apps/alpsbte-web/__mocks__/fileMock.js, jest.preset.js, libs/about-us/__mocks__/fileMock.js, libs/application/__mocks__/fileMock.js, libs/contact/__mocks__/fileMock.js, libs/downloads/__mocks__/fileMock.js, libs/error/__mocks__/fileMock.js, libs/faq/__mocks__/fileMock.js, libs/gallery/__mocks__/fileMock.js, libs/home/__mocks__/fileMock.js, libs/shared/components/__mocks__/fileMock.js, libs/shared/components/src/lib/header/header.tsx
I needed to mock the images and other files with in each lib - which isn't pretty, but it works i guess.
=> Closes #31 - Fix linting and test errors

libs/router/src/lib/router.tsx, libs/shared/components/src/lib/header/header.scss, libs/shared/components/src/lib/header/header.spec.tsx, libs/shared/components/src/lib/header/header.tsx
=> Fix Reload Redirect Issue

libs/router/src/lib/router.tsx, package.json
=> 76 dynamic route definitions

libs/faq/src/components/accordeon/accordeon.scss, libs/faq/src/components/accordeon/accordeon.spec.tsx, libs/faq/src/components/accordeon/accordeon.tsx, libs/faq/src/lib/faq.tsx
=> 48 faq page

libs/loader/src/lib/loader.module.scss, libs/loader/src/lib/loader.scss, libs/loader/src/lib/loader.tsx
Just a simple spinner, nothing fancy
=> 68 loading page

libs/home/src/lib/home.tsx, libs/router/src/lib/router.tsx, libs/shared/components/src/lib/header/header.tsx, libs/shared/components/src/lib/language-select/language-select.scss, libs/shared/components/src/lib/language-select/language-select.spec.tsx, libs/shared/components/src/lib/language-select/language-select.tsx, libs/shared/language/src/lib/types/language.ts, libs/shared/stores/src/lib/stores/language.store.ts
Followup: Implement actual select/dropdown to switch languages. Replace temporary toggle button
=> 73 language system UI followup

libs/home/src/components/home-content-section/home-content-section.scss, libs/home/src/components/home-content-section/home-content-section.tsx, libs/home/src/lib/home.tsx, libs/shared/language/src/lib/interfaces/set.ts, libs/shared/language/src/lib/testdata/de.json, libs/shared/language/src/lib/testdata/en.json, libs/shared/theme/src/lib/mixins/breakpoint.scss, libs/shared/theme/src/lib/mixins/index.scss, libs/shared/theme/src/lib/variables/spacings.scss
=> 90 home page

libs/about-us/src/lib/about-us.scss, libs/contact/src/lib/contact.scss, libs/faq/src/components/accordeon/accordeon.scss, libs/loader/src/lib/loader.scss, libs/shared/components/src/lib/button/button.scss, libs/shared/components/src/lib/header/header.scss, libs/shared/components/src/lib/language-select/language-select.scss, libs/shared/theme/src/lib/variables/spacings.scss
=> 93 fix spacings

libs/home/src/components/home-content-section/home-content-section.scss, libs/home/src/lib/home.scss, libs/home/src/lib/home.tsx, libs/shared/components/src/index.ts, libs/shared/components/src/lib/scroll-indicator/scroll-indicator.module.scss, libs/shared/components/src/lib/scroll-indicator/scroll-indicator.scss, libs/shared/components/src/lib/scroll-indicator/scroll-indicator.spec.tsx, libs/shared/components/src/lib/scroll-indicator/scroll-indicator.tsx, libs/shared/theme/src/lib/mixins/position.scss, libs/shared/theme/src/lib/styles/html.scss
=> 58 scroll indicator

libs/shared/components/src/lib/header/header.tsx, libs/shared/components/src/lib/language-select/language-select.scss, libs/shared/components/src/lib/language-select/language-select.tsx
=> 97 language select color

libs/about-us/src/lib/about-us.scss, libs/about-us/src/lib/about-us.tsx, libs/shared/components/src/lib/page-title/page-title.scss, libs/shared/components/src/lib/page-title/page-title.tsx
=> 99 header background

libs/shared/components/src/lib/header/header.tsx
=> Added language select on mobile version

apps/alpsbte-web/src/index.html
=> added meta tags

libs/shared/components/src/lib/header/header.scss, libs/shared/theme/src/lib/variables/index.scss
Now it looks like in the design
=> Navbar style correction

libs/about-us/src/lib/about-us.tsx, libs/faq/src/lib/faq.tsx, libs/home/src/lib/home.scss, libs/home/src/lib/home.tsx, libs/shared/components/src/lib/button/button.scss, libs/shared/components/src/lib/button/button.tsx, libs/shared/components/src/lib/header/header.scss, libs/shared/components/src/lib/page-title/page-title.spec.tsx, libs/shared/config/src/index.ts, libs/shared/config/src/lib/server.ts, libs/shared/language/src/lib/interfaces/set.ts, libs/shared/language/src/lib/testdata/de.json, libs/shared/language/src/lib/testdata/en.json, libs/shared/theme/src/lib/variables/colors.scss, package-lock.json, package.json
=> Restyle home page buttons

libs/contact/src/lib/contact.tsx
=> Link social media icons

libs/contact/src/lib/contact.scss, libs/contact/src/lib/contact.spec.tsx, libs/contact/src/lib/contact.tsx, libs/faq/src/components/accordeon/accordeon.spec.tsx, libs/faq/src/lib/faq.spec.tsx, libs/shared/components/src/lib/page-title/page-title.scss, libs/shared/components/src/lib/page-title/page-title.tsx, libs/shared/config/src/index.ts, libs/shared/config/src/lib/contact.ts, libs/shared/language/src/lib/interfaces/set.ts, libs/shared/language/src/lib/testdata/de.json, libs/shared/language/src/lib/testdata/en.json, libs/shared/theme/src/lib/styles/p.scss
=> 119 contact finishing touches

libs/about-us/src/lib/about-us.tsx, libs/application/src/components/application-step/application-step.scss, libs/application/src/components/application-step/application-step.spec.tsx, libs/application/src/components/application-step/application-step.tsx, libs/application/src/lib/application.module.scss, libs/application/src/lib/application.scss, libs/application/src/lib/application.spec.tsx, libs/application/src/lib/application.tsx, libs/downloads/src/lib/downloads.spec.tsx, libs/downloads/src/lib/downloads.tsx, libs/home/src/components/home-content-section/home-content-section.scss, libs/home/src/components/home-content-section/home-content-section.tsx, libs/home/src/lib/home.scss, libs/home/src/lib/home.tsx, libs/shared/components/src/lib/page-title/page-title.scss, libs/shared/components/src/lib/page-title/page-title.tsx, libs/shared/language/src/lib/interfaces/set.ts, libs/shared/language/src/lib/testdata/de.json, libs/shared/language/src/lib/testdata/en.json
=> Application page

libs/error/src/lib/error.scss, libs/error/src/lib/error.spec.tsx, libs/error/src/lib/error.tsx, libs/shared/components/src/lib/page-title/page-title.tsx, libs/shared/language/src/lib/interfaces/set.ts, libs/shared/language/src/lib/testdata/de.json, libs/shared/language/src/lib/testdata/en.json
=> Error Page

libs/contact/src/lib/contact.scss, libs/home/src/components/home-content-section/home-content-section.scss, libs/shared/components/src/lib/footer/footer.scss, libs/shared/components/src/lib/header/header.scss, libs/shared/components/src/lib/language-select/language-select.scss, libs/shared/config/src/lib/breakpoints.ts
=> 128 fix spacings on home page

libs/shared/language/src/lib/testdata/fr.json
Small corrections of the language on the website - French translation
=> Corrections French

libs/shared/language/src/lib/testdata/de.json
Alle auf Discord genannten Fehler sind korrigiert ^^
=> Korrekturen
